CREATE TABLE PRODUTOS (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (20),
    VALOR DOUBLE,
    MARCA VARCHAR (20)
);

INSERT INTO PRODUTOS VALUES
(NULL, 'GALAXY S10', 5000, 'SAMSUNG'),
(NULL, 'IPHONE11', 6000, 'APPLE'),
(NULL, 'MOTO G7', 1500, 'MOTOROLA'),
(NULL, 'GALAXY NOTE10', 6500, 'SAMSUNG'),
(NULL, 'IPHONE 8', 3000, 'APLLE');

SELECT * FROM PRODUTOS;

/*
COMANDO PARA SELECIONAR UMA COLUNA DA TABELA SEM REPETIR OS NOMES
(GROUP)
*/
SELECT MARCA FROM PRODUTOS GROUP BY MARCA;

SELECT MARCA, COUNT(*) FROM PRODUTOS GROUP BY MARCA;

SELECT NOME FROM PRODUTOS WHERE MARCA IN ('APPLE', 'SAMSUNG');

SELECT NOME, VALOR FROM PRODUTOS WHERE VALOR < 6000;

INSERT INTO PRODUTOS VALUES (NULL,'IPHONE 11MAX', 6500, 'APLLE');

SELECT NOME, VALOR FROM PRODUTOS WHERE VALOR = (SELECT MAX(VALOR) FROM PRODUTOS);

DELETE FROM PRODUTOS WHERE MARCA = 'SAMSUNG';

INSERT INTO PRODUTOS VALUES
(NULL, 'GALAXY A7', 2000, 'SAMSUNG'),
(NULL, 'GALAXY A8', 2350, 'SAMSUNG');

TRUNCATE TABLE PRODUTOS;

DROP TABLE PRODUTOS