CREATE TABLE ALUNOS (
    NOME VARCHAR (30),
    IDADE INT,
    NOTA1 DOUBLE,
    NOTA2 DOUBLE
);

SELECT * FROM ALUNOS;

INSERT INTO ALUNOS VALUES
('ANA', 15, 7.5, 8.2),
('LUCAS', NULL, 9, 8.6),
('VANESSA', 16, 6.6, 7.1),
('LEONARDO', 15, 5, 4.5),
('DÊNIS', 17, 10, 10);

SELECT * FROM ALUNOS;

SELECT NOME, (NOTA1 + NOTA2)/2 FROM ALUNOS;

SELECT 
  NOME,
  CONCAT (IF ((NOTA1 + NOTA2)/2 >= 7, 'APROVADO', 'REPROVADO'), 'COM MÉDIA', (NOTA1 + NOTA2)/2)
FROM ALUNOS;

SELECT * FROM ALUNOS WHERE IDADE BETWEEN 0 AND 15; 

SELECT NOME FROM ALUNOS ORDER BY NOME DESC;

SELECT NOME FROM ALUNOS WHERE NOME LIKE '%L%';

SELECT NOME FROM ALUNOS WHERE NOME LIKE '%A';

SELECT NOME FROM ALUNOS WHERE NOME LIKE 'A%';

SELECT COUNT (*) FROM ALUNOS;

SELECT SUM(IDADE) FROM ALUNOS;

SELECT MAX (IDADE) FROM ALUNOS;

SELECT MIN (IDADE) FROM ALUNOS;

UPDATE ALUNOS SET IDADE = 15 WHERE IDADE IS NULL;

DELETE FROM ALUNOS WHERE IDADE > 15;

DROP TABLE ALUNOS;