/*
  OPERADORES RELACIONAIS
    > MAIOR
    < MENOR
    >= MEIOR OU IGUAL
    <= MENOR OU IGUAL
    = IGUAL 
    <> DIFERENTE

  OPERADORES LÓGICOS
    E -> AND
    OU -> OR
*/

CREATE TABLE ALUNOS (
    NOME VARCHAR(30),
    NOTA1 FLOAT, 
    NOTA2 FLOAT
);

INSERT INTO  ALUNOS VALUES
('BRUNO',7,8.5),
('CARLA',9,10),
('ELLEN',6,8),
('PAULA',7,5);

SELECT  * FROM ALUNOS;

SELECT NOME, (NOTA1 + NOTA2)/2 FROM ALUNOS;

SELECT NOME FROM ALUNOS ORDER BY NOME DESC;

/*ORDER BY -> ORDENAÇÃO
  ASC -> MENOR/MAIOR OU A/Z
  DESC -> MAIOR/MENOR Z/A
*/

SELECT nome, if ((NOTA1 + NOTA2)/2 >= 7, 'APROVADO', 'RREPROVADO') FROM ALUNOS;

SELECT 
    NOME, 
    CONCAT (if ((NOTA1 + NOTA2)/2 >= 7, 'APROVADO', 'REPROVADO'),' COM MÉDIA ', (NOTA + NOTA2)/2)
FROM ALUNOS;

SELECT COUNT (*) FROM ALUNOS;

SELECT MAX (NOTA1) FROM ALUNOS;

SELECT MIN (NOTA1) FROM alunos;

SELECT  AVG (NOTA1) FROM ALUNOS;

SELECT NOME, NOTA1 FROM ALUNOS WHERE NOTA1 >= 7;

/*
  %A -> INICIA COM O TERMO
  A% -> FINALIZA COM O TERMO
  %U% -> CONTEM O TERMO
*/

SELECT NOME FROM ALUNOS WHERE NOME LIKE '%U%';

UPDATE ALUNOS SET NOTA2 = 7 WHERE NOME = 'PAULA';

DELETE FROM ALUNOS WHERE NOME = 'CARLA';

DROP TABLE ALUNOS;