CREATE TABLE PRODUTOS(
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (40),
    VALOR DECIMAL (10,2),
    MARCA VARCHAR (30)
);

INSERT INTO PRODUTOS VALUES
(NULL, 'IPHONE X', 4000, 'APPLE'),
(NULL, 'GALAXY S21', 4300,'SAMSUNG'),
(NULL, 'TV NANOCELL 50', 2699, 'LG'),
(NULL, 'PLAYSTATION 5', 5000, 'SONY'),
(NULL, 'NOTEBOOK INSPIRON', 4100, 'DELL');

SELECT * FROM PRODUTOS;

INSERT INTO PRODUTOS VALUES (5, 'TV', 1000, 'SONY');

SELECT NOME FROM PRODUTOS WHERE MARCA IN ('SAMSUNG', 'LG', 'SONY');

SELECT * FROM PRODUTOS WHERE VALOR BETWEEN  2500 AND 4000;

INSERT INTO PRODUTOS VALUES (NULL, 'TECLADO', NULL, 'MICROSOFT');

SELECT * FROM PRODUTOS WHERE VALOR IS NULL;
SELECT * FROM PRODUTOS WHERE VALOR IS NOT NULL;

TRUNCATE TABLE PRODUTOS;