CREATE TABLE CARGOS (
  CODIGOCARGO INT AUTO_INCREMENT  PRIMARY KEY,
  NOMECARGO VARCHAR (30)
);

INSERT INTO CARGOS VALUES
(NULL, 'DESENVOLVEDOR'),
(NULL, 'ANALISTA'),
(NULL, 'GERENTE');

CREATE TABLE COLABORADORES (
  CODIGOCOLABORADOR INT AUTO_INCREMENT PRIMARY KEY,
  NOMECOLABORADOR VARCHAR (40),
  CODIGOCARGO INT,
  FOREIGN KEY (CODIGOCARGO) REFERENCES CARGOS (CODIGOCARGO)
);

SELECT * FROM CARGOS;

INSERT INTO COLABORADORES (NOMECOLABORADOR, CODIGOCARGO) VALUES
('SARAH', 1),
('EVERTON', 1),
('CHRISTIAN', 2),
('JÉSSICA', 1);

SELECT
    COLABORADORES.NOMECOLABORADOR,
    CARGOS.NOMECARGO
FROM colaboradores
INNER JOIN CARGOS
ON CARGOS.CODIGOCARGO = COLABORADORES.CODIGOCARGO;

SELECT 
    CARGOS.NOMECARGO,
   COUNT (COLABORADORES.CODIGOCARGO)
FROM COLABORADORES
RIGHT JOIN CARGOS
ON CARGOS.CODIGOCARGO = COLABORADORES.CODIGOCARGO
GROUP BY CARGOS.CODIGOCARGO;

INSERT INTO colaboradores VALUES (NULL, 'LUANA', NULL);

SELECT 
    cargos.nomecargo,
    colaboradores.nomecolaborador
FROM colaboradores
LEFT JOIN cargos
ON cargos.codigocargo = colaboradores.codigocargo;