CREATE TABLE ESTADOS(
  CODIGOESTADO INT AUTO_INCREMENT PRIMARY KEY,
  NOMEESTADO VARCHAR (30)
);

INSERT INTO ESTADOS (NOMEESTADO) VALUES
('PARANÁ'),
('RIO GRANDE DO SUL'),
('RIO DE JANEIRO'),
('SANTA CATARINA'),
('SÃO PAULO');

CREATE TABLE CIDADES(
  CODIGOCIDADE INT AUTO_INCREMENT PRIMARY KEY,
  NOMECIDADE VARCHAR (40),
  CODIGOESTADO INT,
  FOREIGN KEY (CODIGOESTADO) REFERENCES ESTADOS(CODIGOESTADO)
);


TRUNCATE TABLE CIDADES;
INSERT INTO CIDADES (NOMECIDADE, CODIGOESTADO) VALUES
('CURITIBA', 1),
('PORTO ALEGRE', 2),
('FLORIANÓPOLIS', 4),
('BLUMENAU', 4),
('LONDRINA', 1);

CREATE TABLE PESSOAS (
  CODIGOPESSOA INT AUTO_INCREMENT PRIMARY KEY,
  NOMEPESSOA VARCHAR (40),
  CODIGOESTADO INT,
  CODIGOCIDADE INT,
  FOREIGN KEY (CODIGOESTADO) REFERENCES ESTADOS (CODIGOESTADO),
  FOREIGN KEY (CODIGOCIDADE) REFERENCES CIDADES (CODIGOCIDADE)
);


INSERT INTO PESSOAS (NOMEPESSOA, CODIGOESTADO, CODIGOCIDADE) VALUES
('ADRIANE', 1, 5),
('LUCAS', 4, 4),
('VANESSA',1, 5);
CREATE  VIEW SELECIONAR AS
SELECT
  PESSOAS.CODIGOPESSOA,
  PESSOAS.NOMEPESSOA,
  ESTADOS.NOMEESTADO,
  CIDADES.NOMECIDADE
FROM PESSOAS
INNER JOIN ESTADOS 
ON ESTADOS.CODIGOESTADO = PESSOAS.CODIGOESTADO
INNER JOIN CIDADES
ON CIDADES.CODIGOCIDADE = PESSOAS.CODIGOCIDADE;

SELECT * FROM SELECIONAR;